# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35a55927541dc6c3b28c2cdc7cfd753f96571dc2dbd15dc7343b73b4fab641c9dd33ed734254648e103dd55704bb2289be0bac9530ab1a490daaf424aad4bdcd

test:
  secret_key_base: e80e2ba29a7fb9fa03ba7712a2cdc899d8e1be7d966d2cf346b3b5d0b626bfe6e49b503b891503b647c3b7a463429cb0544393b7bfa41d3808b1ced40e929e8f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
